# Target database with NASR data
nasr_db:
  # host name/ip
  host: "localhost"
  # database name
  database: "faa_nasr_dev"
  # user name
  user: ""
  # password for the user
  password: ""
# Global CSV settings for reading NASR CSV files
csv_settings:
  # Encoding to use for UTF when reading file
  encoding: "utf-8"
  # delimiter character to separate CSV columns
  delimiter: ","
  # Character used to denote the start and end of a quoted item
  quote_char: '"'
# Path to the directory with NASR CSV files
data_dir: "nasr_data/27_Nov_2025_CSV"
# Definition of 'dictionary' tables, e.g. used for storing FIX use code, RADAR types etc.
# Includes data to be loaded into table as list of dictionaries with:
# key - column name
# value - value to be stored in this table
dict_tables:
#  - name: "table1"
#    data:
#      - col1: "value_col1_row1"
#        col2: "value_col2_row1"
#        col3: "value_col3_row1"
#      - col1: "value_col1_row2"
#        col2: "value_col2_row2"
#        col3: "value_col3_row2"
  - name: "fix_use_code"
    data:
      - code: "CN"
        desc: "COMPUTER NAVIGATION FIX"
      - code: "MR"
        desc: "MILITARY REPORTING POINT"
      - code: "MW"
        desc: "MILITARY WAYPOINT"
      - code: "NRS"
        desc: "NRS WAYPOINT"
      - code: "RADAR"
        desc: "RADAR"
      - code: "RP"
        desc: "REPORTING POINT"
      - code: "VFR"
        desc: "VFR WAYPOINT"
      - code: "WP"
        desc: "WAYPOINT"
  - name: "rdr_type"
    data:
      - code: "ARSR"
        desc: "AIR ROUTE SURVEILLANCE RADAR"
      - code: "ASR"
        desc: "AIRPORT SURVEILLANCE RADAR (-# DENOTES TYPE OF ASR)"
      - code: "ASR/PAR"
        desc: "AIRPORT SURVEILLANCE RADAR PLUS PRECISION APPROACH RADAR"
      - code: "GCA"
        desc: "GROUND CONTROL APPROACH"
      - code: "PAR"
        desc: "PRECISION APPROACH RADAR"
      - code: "SECRA"
        desc: "SECONDARY RADAR"
      - code: "BCN"
        desc: "BEACON RADAR"
data_tables:
# Definition of 'data' tables -
#  - file_name: "file1.csv"
#    table_name: "file1"
#    is_spatial: true
#    columns:
#      - "COL1"
#      - "COL2"
#      - "COL3"
  - file_name: "FIX_BASE.csv"
    table_name: "fix"
    is_spatial: true
    columns:
      - "FIX_ID"
      - "ICAO_REGION_CODE"
      - "STATE_CODE"
      - "COUNTRY_CODE"
      - "LAT_DECIMAL"
      - "LONG_DECIMAL"
      - "FIX_ID_OLD"
      - "CHARTING_REMARK"
      - "FIX_USE_CODE"
      - "ARTCC_ID_HIGH"
      - "ARTCC_ID_LOW"
      - "PITCH_FLAG"
      - "CATCH_FLAG"
      - "SUA_ATCAA_FLAG"
      - "MIN_RECEP_ALT"
      - "COMPULSORY"
  - file_name: "FIX_CHRT.csv"
    table_name: "fix_chrt"
    is_spatial: false
    columns:
      - "FIX_ID"
      - "CHARTING_TYPE_DESC"
  - file_name: "FIX_NAV.csv"
    table_name: "fix_nav"
    is_spatial: false
    columns:
      - "FIX_ID"
      - "NAV_ID"
      - "BEARING"
      - "DISTANCE"
  - file_name: "RDR.csv"
    table_name: "rdr"
    is_spatial: false
    columns:
      - "FACILITY_ID"
      - "FACILITY_TYPE"
      - "STATE_CODE"
      - "COUNTRY_CODE"
      - "RADAR_TYPE"
      - "RADAR_NO"
      - "RADAR_HRS"
      - "REMARK"