# Target database with NASR data
nasr_db:
  # host name/ip
  host: "localhost"
  # database name
  database: "faa_nasr_dev"
  # user name
  user: ""
  # password for the user
  password: ""
# Global CSV settings for reading NASR CSV files
csv_settings:
  # Encoding to use for UTF when reading file
  encoding: "utf-8"
  # delimiter character to separate CSV columns
  delimiter: ","
  # Character used to denote the start and end of a quoted item
  quote_char: '"'
# Path to the directory with NASR CSV files
data_dir: "nasr_data/27_Nov_2025_CSV"
# Definition of 'dictionary' tables, e.g. used for storing FIX use code, RADAR types etc.
# Includes data to be loaded into table as list of dictionaries with:
# key - column name
# value - value to be stored in this table
dict_tables:
#  - name: "table1"
#    data:
#      - col1: "value_col1_row1"
#        col2: "value_col2_row1"
#        col3: "value_col3_row1"
#      - col1: "value_col1_row2"
#        col2: "value_col2_row2"
#        col3: "value_col3_row2"
  - name: "fix_use_code"
    data:
      - code: "CN"
        desc: "COMPUTER NAVIGATION FIX"
      - code: "MR"
        desc: "MILITARY REPORTING POINT"
      - code: "MW"
        desc: "MILITARY WAYPOINT"
      - code: "NRS"
        desc: "NRS WAYPOINT"
      - code: "RADAR"
        desc: "RADAR"
      - code: "RP"
        desc: "REPORTING POINT"
      - code: "VFR"
        desc: "VFR WAYPOINT"
      - code: "WP"
        desc: "WAYPOINT"
  # Navigation Aids (NAV)
  - name: "navaid_type"
    data:
      - nav_type: "CONSOLAN"
        description: "A Low Frequency, Long-Distance NAVAID Used Principally for Transoceanic navigation."
      - nav_type: "DME"
        description: "Distance Measuring Equipment only."
      - nav_type: "FAN MARKER"
        description: "There are 3 types of EN ROUTE Market Beacons.  FAN MARKER, Low powered FAN MARKERS and Z MARKERS.  A FAN MARKER Is used to provide a positive identification of positions at Definite points along the airways."
      - nav_type: "MARINE NDB"
        description: "A NON Directional Beacon used primarily for Marine (surface) Navigation."
      - nav_type: "MARINE NDB/DME"
        description: "  A NON Directional Beacon with associated Distance measuring Equipment; used primarily for Marine (surface) Navigation."
      - nav_type: "NDB"
        description: "A NON Directional Beacon"
      - nav_type: "NDB/DME"
        description: "Non Directional Beacon with associated Distance Measuring Equipment."
      - nav_type: "TACAN"
        description: "A Tactical Air Navigation System providing Azimuth and Slant Range Distance."
      - nav_type: "UHF/NDB"
        description: "Ultra High Frequency/NON Directional Beacon."
      - nav_type: "VOR"
        description: "A VHF OMNI-Directional Range providing Azimuth only."
      - nav_type: "VORTAC"
        description: "A Facility consisting of two components, VOR and TACAN, Which provides three individual services: VOR AZIMITH, TACAN AZIMUTH and TACAN Distance (DME) at one site."
      - nav_type: "VOR/DME"
        description: "VHF OMNI-DIRECTIONAL Range with associated Distance Measuring equipment."
      - nav_type: "VOT"
        description: "A FAA VOR Test Facility."
  - name: "faa_region_code"
    data:
      - region_code: "AAL"
        description: "ALASKA"
      - region_code: "ACE"
        description: "CENTRAL"
      - region_code: "AEA"
        description: "EASTERN"
      - region_code: "AGL"
        description: "GREAT LAKES"
      - region_code: "ANE"
        description: "NEW ENGLAND"
      - region_code: "ANM"
        description: "NORTHWEST MOUNTAIN"
      - region_code: "ASO"
        description: "SOUTHERN"
      - region_code: "ASW"
        description: "SOUTHWEST"
      - region_code: "AWP"
        description: "WESTERN-PACIFIC"
  - name: "survey_accuracy_code"
    data:
      - code: "0"
        description: "UNKNOWN"
      - code: "1"
        description: "DEGREE"
      - code: "2"
        description: "10 MINUTES"
      - code: "3"
        description: "1 MINUTE"
      - code: "4"
        description: "10 SECONDS"
      - code: "5"
        description: "1 SECOND OR BETTER"
      - code: "6"
        description: "NOS"
      - code: "7"
        description: "3RD ORDER TRIANGULATION"
  - name: "monitoring_category"
    data:
      - code: "1"
        description: "Internal Monitoring Plus A Status Indicator Installed At Control Point. (Reverts to a Temporary Category 3 Status When the Control Point is not is Not Manned.)"
      - code: "2"
        description: "Internal Monitoring with Status Indicator at Control Point Inoperative but Pilot Reports Indicate facility is operating normally.  (This Is A Temporary Situation That Requires No Procedural Action.)"
      - code: "3"
        description: "Internal Monitoring Only. Status Indicator Non installed at control point."
      - code: "4"
        description: "Internal Monitor Not Installed. Remote Status indicator provided at control point. This Category Is Applicable Only To Non-Directional Beacons."
  - name: "air_gnd_code"
    data:
      - code: "A"
        description: "Air"
      - code: "G"
        description: "Ground"
      - code: "G1"
        description: "Ground One"
  - name: "rdr_type"
    data:
      - code: "ARSR"
        desc: "AIR ROUTE SURVEILLANCE RADAR"
      - code: "ASR"
        desc: "AIRPORT SURVEILLANCE RADAR (-# DENOTES TYPE OF ASR)"
      - code: "ASR/PAR"
        desc: "AIRPORT SURVEILLANCE RADAR PLUS PRECISION APPROACH RADAR"
      - code: "GCA"
        desc: "GROUND CONTROL APPROACH"
      - code: "PAR"
        desc: "PRECISION APPROACH RADAR"
      - code: "SECRA"
        desc: "SECONDARY RADAR"
      - code: "BCN"
        desc: "BEACON RADAR"
  - name: "wxl_survey_method"
    data:
      - code: "S"
        desc: "VALUE WAS SURVEYED"
      - code: "E"
        desc: "VALUE WAS ESTIMATED"
  - name: "wxl_wea_svc_type"
    data:
      - code: "AC"
        desc: "SEVERE WEATHER OUTLOOK NARRATIVE"
      - code: "AWW"
        desc: "SEVERE WEATHER FORECAST ALERT"
      - code: "CWA"
        desc: "CENTRAL WEATHER ADVISORY"
      - code: "FA"
        desc: "AREA FORECAST"
      - code: "FD"
        desc: "WINDS & TEMPERATURE ALOFT FORECAST"
      - code: "FT"
        desc: "AVIATION TERMINAL FORECAST"
      - code: "FX"
        desc: "MISCELLANEOUS FORECASTS"
      - code: "METAR"
        desc: "AVIATION ROUTINE WEATHER REPORT (ICAO)"
      - code: "MIS"
        desc: "METEOROLOGICAL IMPACT SUMMARY"
      - code: "NOTAM"
        desc: "NOTICE TO AIRMEN"
      - code: "SA"
        desc: "SURFACE OBSERVATION REPORT"
      - code: "SD"
        desc: "RADAR WEATHER REPORT"
      - code: "SPECI"
        desc: "AVIATION SPECIAL WEATHER REPORT (ICAO)"
      - code: "SYNS"
        desc: "TRANSCRIBED WEATHER BROADCAST SYNOPSES"
      - code: "TAF"
        desc: "AVIATION TERMINAL FORECAST (ICAO)"
      - code: "TWEB"
        desc: "TRANSCRIBED WEATHER BROADCAST"
      - code: "UA"
        desc: "AIRCRAFT REPORT (PIREP)"
      - code: "WA"
        desc: "WEATHER ADVISORY"
      - code: "WH"
        desc: "ABBREVIATED HURRICANE ADVISORY"
      - code: "WO"
        desc: "TROPICAL DEPRESSIONS"
      - code: "WS"
        desc: "FLIGHT ADVISORY - SIGMET"
      - code: "WST"
        desc: "CONVECTIVE SIGMET"
      - code: "WW"
        desc: "SEVERE WEATHER BROADCASTS OR BULLETINS"
data_tables:
# Definition of 'data' tables -
#  - file_name: "file1.csv"
#    table_name: "file1"
#    is_spatial: true
#    columns:
#      - "COL1"
#      - "COL2"
#      - "COL3"
  - file_name: "AWOS.csv"
    table_name: "awos"
    is_spatial: true
    columns:
      - "ASOS_AWOS_ID"
      - "ASOS_AWOS_TYPE"
      - "STATE_CODE"
      - "CITY"
      - "COUNTRY_CODE"
      - "COMMISSIONED_DATE"
      - "NAVAID_FLAG"
      - "LAT_DECIMAL"
      - "LONG_DECIMAL"
      - "ELEV"
      - "SURVEY_METHOD_CODE"
      - "PHONE_NO"
      - "SECOND_PHONE_NO"
      - "SITE_NO"
      - "SITE_TYPE_CODE"
      - "REMARK"
  - file_name: "FIX_BASE.csv"
    table_name: "fix"
    is_spatial: true
    columns:
      - "FIX_ID"
      - "ICAO_REGION_CODE"
      - "STATE_CODE"
      - "COUNTRY_CODE"
      - "LAT_DECIMAL"
      - "LONG_DECIMAL"
      - "FIX_ID_OLD"
      - "CHARTING_REMARK"
      - "FIX_USE_CODE"
      - "ARTCC_ID_HIGH"
      - "ARTCC_ID_LOW"
      - "PITCH_FLAG"
      - "CATCH_FLAG"
      - "SUA_ATCAA_FLAG"
      - "MIN_RECEP_ALT"
      - "COMPULSORY"
  - file_name: "FIX_CHRT.csv"
    table_name: "fix_chrt"
    is_spatial: false
    columns:
      - "FIX_ID"
      - "CHARTING_TYPE_DESC"
  - file_name: "FIX_NAV.csv"
    table_name: "fix_nav"
    is_spatial: false
    columns:
      - "FIX_ID"
      - "NAV_ID"
      - "BEARING"
      - "DISTANCE"
  # Navigation Aids (NAV)
  - file_name: "NAV_BASE.csv"
    table_name: "navaid"
    is_spatial: true
    columns:
      - "NAV_ID"
      - "NAV_TYPE"
      - "COUNTRY_CODE"
      - "CITY"
      - "REGION_CODE"
      - "FAN_MARKER"
      - "OWNER"
      - "OPERATOR"
      - "NAS_USE_FLAG"
      - "PUBLIC_USE_FLAG"
      - "NDB_CLASS_CODE"
      - "OPER_HOURS"
      - "HIGH_ALT_ARTCC_ID"
      - "HIGH_ARTCC_NAME"
      - "LOW_ALT_ARTCC_ID"
      - "LOW_ARTCC_NAME"
      - "LAT_DECIMAL"
      - "LONG_DECIMAL"
      - "SURVEY_ACCURACY_CODE"
      - "ELEV"
      - "MAG_VARN"
      - "MAG_VARN_HEMIS"
      - "MAG_VARN_YEAR"
      - "SIMUL_VOICE_FLAG"
      - "PWR_OUTPUT"
      - "AUTO_VOICE_ID_FLAG"
      - "MNT_CAT_CODE"
      - "VOICE_CALL"
      - "CHAN"
      - "FREQ"
      - "MKR_IDENT"
      - "MKR_SHAPE"
      - "MKR_BRG"
      - "ALT_CODE"
      - "LOW_NAV_ON_HIGH_CHART_FLAG"
      - "Z_MKR_FLAG"
      - "FSS_ID"
      - "FSS_NAME"
      - "FSS_HOURS"
      - "NOTAM_ID"
      - "QUAD_IDENT"
      - "PITCH_FLAG"
      - "CATCH_FLAG"
      - "SUA_ATCAA_FLAG"
      - "RESTRICTION_FLAG"
      - "HIWAS_FLAG"
  - file_name: "NAV_CKPT.csv"
    table_name: "navaid_checkpoint"
    is_spatial: false
    columns:
      - "NAV_ID"
      - "NAV_TYPE"
      - "COUNTRY_CODE"
      - "CITY"
      - "ALTITUDE"
      - "BRG"
      - "AIR_GND_CODE"
      - "CHK_DESC"
      - "ARPT_ID"
  - file_name: "NAV_RMK.csv"
    table_name: "navaid_remark"
    is_spatial: false
    columns:
      - "NAV_ID"
      - "NAV_TYPE"
      - "COUNTRY_CODE"
      - "CITY"
      - "TAB_NAME"
      - "REF_COL_NAME"
      - "REF_COL_SEQ_NO"
      - "REMARK"
  - file_name: "RDR.csv"
    table_name: "rdr"
    is_spatial: false
    columns:
      - "FACILITY_ID"
      - "FACILITY_TYPE"
      - "STATE_CODE"
      - "COUNTRY_CODE"
      - "RADAR_TYPE"
      - "RADAR_NO"
      - "RADAR_HRS"
      - "REMARK"
  - file_name: "WXL_BASE.csv"
    table_name: "wxl"
    is_spatial: true
    columns:
      - "WEA_ID"
      - "CITY"
      - "STATE_CODE"
      - "COUNTRY_CODE"
      - "LAT_DECIMAL"
      - "LONG_DECIMAL"
      - "ELEV"
      - "SURVEY_METHOD_CODE"
  - file_name: "WXL_SVC.csv"
    table_name: "wxl_svc"
    is_spatial: false
    columns:
      - "WEA_ID"
      - "WEA_SVC_TYPE_CODE"
      - "WEA_AFFECT_AREA"
